
os: osx
osx_image: xcode11.1
language: swift
script: xcodebuild clean build test -project Evrlogger.xcodeproj -scheme "EvrLogger" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.1,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO